apiVersion: v1
kind: ConfigMap
metadata:
  name: aide-bot-config
  namespace: apps
  labels:
    app.kubernetes.io/name: aide-bot
data:
  APP_NAME: aide-bot
  APP_ENV: production
  LOG_LEVEL: INFO
  BACKEND_API_BASE_URL: https://api-aide.icho.su
  BACKEND_CLEAR_HISTORY_PATH: ""
  BACKEND_MESSAGES_PATH: ""
  BACKEND_STUB: "false"
  BACKEND_REQUEST_TIMEOUT: 45s
  MAX_API_BASE_URL: ""
  MAX_REQUEST_TIMEOUT: 45s
  MAX_POLLING_PAUSE: 500ms
  MAX_POLLING_TIMEOUT: 30s
